public class Main{

    /*
    void errorFunc(){
        try {
            // The following statement throws NumberFormatException
        int luckNumber = Integer.parseInt("Hello");
        } catch (Exception e) {
        // Handle the exception here
        } catch (NumberFormatException e) {
        // Handle the exception here
        }
    }
    */



    public static void main(String[] args) {
        Main obj = new Main();
        
        //obj.errorFunc();


    }
}
//code does not compile because NumberFormatExption is child class of Exeption 